project:
  type: website
  output-dir: docs 

format:
  clean-revealjs:
    self-contained: true
    transition: slide
    slide-number: c/t

bibliography: references/refs.bib
csl: references/nature.csl
citeproc: true
link-citations: true

execute:
  echo: true
  warning: false

render:
  - index.qmd
  - slides/gomulkiewicz.qmd
  - slides/toc.qmd
  - slides/adaptation.qmd 
  - slides/ML.qmd
  - slides/campanula.qmd
  - slides/woah.qmd
